# Generated by Django 2.0.1 on 2018-01-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('day', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEveryDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEveryWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('week_day', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEveryYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TimesForEveryDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=5)),
                ('repeat_count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='scheduleeveryday',
            name='times',
            field=models.ManyToManyField(to='vkbot_schedule.TimesForEveryDay'),
        ),
    ]
